import type { Metadata } from "next"
import type { ReactNode } from "react"

import { ThemeProvider } from "@1st/components"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider forcedTheme={"light"}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
